// Generated by scripts/sync-edge-shared.mjs; edit src/lib/content.ts.
// 原创解读文案库：只覆盖核心组合，其余由模板按命盘特征拼接。
import type { AspectType, Mutagen, PlanetKey } from './types.ts';

export interface Trait { keywords: string[]; gift: string; shadow: string; advice: string }

// ---------- 紫微：十四主星 ----------
export const ZIWEI_STARS: Record<string, Trait> = {
  紫微: { keywords: ['主导', '格局', '自尊'], gift: '天生愿意扛事，能把散乱的局面收拢成秩序。', shadow: '容易把面子放在感受前面，不愿示弱。', advice: '先听完再拍板，你的判断会更稳。' },
  天机: { keywords: ['思考', '变化', '策划'], gift: '反应快，擅长发现流程里的漏洞和捷径。', shadow: '想得太多，容易在选项之间来回摇摆。', advice: '给自己设一个决定的截止时间。' },
  太阳: { keywords: ['付出', '外显', '热度'], gift: '乐于照亮别人，在人群里有感染力。', shadow: '付出多了会累，却不好意思开口要回报。', advice: '把“我也需要被照顾”说出来。' },
  武曲: { keywords: ['执行', '财务', '果断'], gift: '目标清晰，落地能力强，对数字敏感。', shadow: '说话直，有时让人觉得不近人情。', advice: '在结论前加一句你的出发点。' },
  天同: { keywords: ['温和', '享受', '修复'], gift: '能让紧张的气氛松下来，人缘柔和。', shadow: '遇到压力时倾向拖延和回避。', advice: '把大任务切成能马上开始的小块。' },
  廉贞: { keywords: ['原则', '魅力', '张力'], gift: '有强烈的个人风格，能在规则里找到突破口。', shadow: '情绪起伏明显，爱憎分明。', advice: '给强烈的情绪留一点缓冲时间。' },
  天府: { keywords: ['稳健', '储备', '包容'], gift: '擅长守成和整合资源，让人有安全感。', shadow: '求稳过头会错过窗口期。', advice: '每季度给自己一次小冒险的预算。' },
  太阴: { keywords: ['细腻', '积累', '内省'], gift: '感受力强，善于长期、安静地积累。', shadow: '心事藏得深，容易独自消化情绪。', advice: '找一个固定的出口写下或说出感受。' },
  贪狼: { keywords: ['欲望', '社交', '多才'], gift: '兴趣广，学习新东西快，懂得享受生活。', shadow: '注意力分散，容易被新鲜感牵着走。', advice: '在三个兴趣里挑一个做深。' },
  巨门: { keywords: ['表达', '分析', '质疑'], gift: '看问题犀利，适合研究、辩论和咨询。', shadow: '言语容易引起误会或口舌。', advice: '质疑事情，而不是质疑人。' },
  天相: { keywords: ['协调', '公正', '体面'], gift: '擅长平衡各方，是可靠的合作者。', shadow: '太在意别人的看法，自己的立场变模糊。', advice: '先确认自己真正想要的结果。' },
  天梁: { keywords: ['庇护', '经验', '原则'], gift: '有长者气质，愿意为别人出主意、兜底。', shadow: '容易好为人师，或替别人操心太多。', advice: '帮忙前先问对方要不要建议。' },
  七杀: { keywords: ['开拓', '冲劲', '独立'], gift: '敢闯敢拼，越到关键时刻越有爆发力。', shadow: '冲得太快，忽略身边人的节奏。', advice: '行动前花五分钟同步一下队友。' },
  破军: { keywords: ['变革', '破旧', '重来'], gift: '不怕推倒重来，能在混乱里开新局。', shadow: '对稳定的东西缺乏耐心。', advice: '改变前先留好退路和存档。' },
};

export const STAR_GROUP: Record<string, '杀破狼' | '紫府廉武相' | '机月同梁' | '巨日'> = {
  七杀: '杀破狼', 破军: '杀破狼', 贪狼: '杀破狼',
  紫微: '紫府廉武相', 天府: '紫府廉武相', 廉贞: '紫府廉武相', 武曲: '紫府廉武相', 天相: '紫府廉武相',
  天机: '机月同梁', 太阴: '机月同梁', 天同: '机月同梁', 天梁: '机月同梁',
  巨门: '巨日', 太阳: '巨日',
};

export const GROUP_STYLE: Record<string, string> = {
  杀破狼: '变动型，节奏快，喜欢开拓',
  紫府廉武相: '统御型，重格局和结果',
  机月同梁: '稳定型，重安全感和细水长流',
  巨日: '表达型，重沟通和公开的认可',
};

// ---------- 紫微：十二宫 ----------
export const PALACES: Record<string, string> = {
  命宫: '你的核心性格与人生基调。',
  兄弟宫: '同辈、伙伴和合作关系。',
  夫妻宫: '亲密关系与你理想中的伴侣形象。',
  子女宫: '创造力、晚辈以及你如何表达热情。',
  财帛宫: '赚钱方式与金钱观。',
  疾厄宫: '身体节律与压力的出口。',
  迁移宫: '外出、远方和你在外人眼中的样子。',
  仆役宫: '朋友圈、团队和人脉资源。',
  官禄宫: '事业方向与做事风格。',
  田宅宫: '家庭、居所和安全感的来源。',
  福德宫: '精神世界、兴趣和内在的满足感。',
  父母宫: '长辈、上级与成长环境。',
};

export const MUTAGEN_TEXT: Record<Mutagen, { name: string; meaning: string }> = {
  禄: { name: '化禄', meaning: '资源和顺遂，事情容易有收获' },
  权: { name: '化权', meaning: '掌控与推动力，适合主动争取' },
  科: { name: '化科', meaning: '名声与贵人，适合展示和学习' },
  忌: { name: '化忌', meaning: '执念与课题，需要多花心思的地方' },
};

// ---------- 西方：行星、星座、宫位、相位 ----------
export const PLANET_INFO: Record<PlanetKey | 'ASC' | 'MC', { name: string; glyph: string; theme: string }> = {
  Sun: { name: '太阳', glyph: '☉', theme: '自我意识与生命力' },
  Moon: { name: '月亮', glyph: '☽', theme: '情绪需求与安全感' },
  Mercury: { name: '水星', glyph: '☿', theme: '思考与沟通' },
  Venus: { name: '金星', glyph: '♀', theme: '爱、审美与价值' },
  Mars: { name: '火星', glyph: '♂', theme: '行动力与欲望' },
  Jupiter: { name: '木星', glyph: '♃', theme: '扩张、机会与信念' },
  Saturn: { name: '土星', glyph: '♄', theme: '责任、边界与时间' },
  Uranus: { name: '天王星', glyph: '♅', theme: '突破与意外' },
  Neptune: { name: '海王星', glyph: '♆', theme: '想象、理想与迷雾' },
  Pluto: { name: '冥王星', glyph: '♇', theme: '深层转化与力量' },
  ASC: { name: '上升', glyph: 'AC', theme: '给人的第一印象' },
  MC: { name: '天顶', glyph: 'MC', theme: '公众形象与志向' },
};

export interface SignInfo { name: string; glyph: string; element: '火' | '土' | '风' | '水'; modality: '本位' | '固定' | '变动'; trait: string }
export const SIGNS: SignInfo[] = [
  { name: '白羊座', glyph: '♈', element: '火', modality: '本位', trait: '直接、急切、敢先开始' },
  { name: '金牛座', glyph: '♉', element: '土', modality: '固定', trait: '踏实、重感官、慢热而持久' },
  { name: '双子座', glyph: '♊', element: '风', modality: '变动', trait: '好奇、灵活、需要信息流' },
  { name: '巨蟹座', glyph: '♋', element: '水', modality: '本位', trait: '护短、念旧、重视归属' },
  { name: '狮子座', glyph: '♌', element: '火', modality: '固定', trait: '大方、需要被看见、有舞台感' },
  { name: '处女座', glyph: '♍', element: '土', modality: '变动', trait: '细致、务实、追求改进' },
  { name: '天秤座', glyph: '♎', element: '风', modality: '本位', trait: '重平衡、审美好、在意关系' },
  { name: '天蝎座', glyph: '♏', element: '水', modality: '固定', trait: '专注、深刻、要么不做要么到底' },
  { name: '射手座', glyph: '♐', element: '火', modality: '变动', trait: '乐观、爱自由、追问意义' },
  { name: '摩羯座', glyph: '♑', element: '土', modality: '本位', trait: '自律、长线、目标导向' },
  { name: '水瓶座', glyph: '♒', element: '风', modality: '固定', trait: '独立、理性、关心群体' },
  { name: '双鱼座', glyph: '♓', element: '水', modality: '变动', trait: '共情、浪漫、边界柔软' },
];

export const HOUSES: string[] = [
  '自我与外在形象', '金钱与自我价值', '沟通与学习', '家庭与根基',
  '创造、恋爱与玩乐', '日常工作与健康习惯', '伴侣与合作', '共享资源与亲密',
  '远行、信念与高等教育', '事业与社会角色', '朋友与社群', '潜意识与独处',
];

export const ASPECT_INFO: Record<AspectType, { name: string; symbol: string; tone: 'soft' | 'hard' | 'neutral'; text: string }> = {
  conjunction: { name: '合相', symbol: '☌', tone: 'neutral', text: '两股力量融合，放大彼此' },
  sextile: { name: '六合', symbol: '⚹', tone: 'soft', text: '有机会互相成就，需要主动' },
  square: { name: '刑相', symbol: '□', tone: 'hard', text: '摩擦带来压力，也带来成长' },
  trine: { name: '拱相', symbol: '△', tone: 'soft', text: '自然流动，顺手的天赋' },
  opposition: { name: '冲相', symbol: '☍', tone: 'hard', text: '两端拉扯，需要找到平衡' },
};

export const pname = (k: string) => PLANET_INFO[k as PlanetKey]?.name ?? k;
export const signName = (i: number) => SIGNS[((i % 12) + 12) % 12].name;
export const fmtDeg = (d: number) => `${Math.floor(d)}°${String(Math.floor((d % 1) * 60)).padStart(2, '0')}′`;
